In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error ,  mean_absolute_error , mean_squared_error

In [5]:
df=pd.read_csv('FuelConsumption.csv')
df.head()

   MODELYEAR   MAKE  ... FUELCONSUMPTION_COMB_MPG CO2EMISSIONS
0       2014  ACURA  ...                       33          196
1       2014  ACURA  ...                       29          221
2       2014  ACURA  ...                       48          136
3       2014  ACURA  ...                       25          255
4       2014  ACURA  ...                       27          244

[5 rows x 13 columns]

In [6]:
column_set=[
    ['FUELCONSUMPTION_COMB_MPG'],
    ['FUELCONSUMPTION_COMB'],
    ['FUELCONSUMPTION_HWY'],
    ['FUELCONSUMPTION_COMB_MPG','FUELCONSUMPTION_COMB'],
    ['FUELCONSUMPTION_COMB_MPG','FUELCONSUMPTION_HWY'],
    ['FUELCONSUMPTION_COMB','FUELCONSUMPTION_HWY'],
    ['FUELCONSUMPTION_COMB_MPG','FUELCONSUMPTION_COMB','FUELCONSUMPTION_HWY']
]
len(column_set)

7

In [16]:
metrics=[]
for item in column_set:
    x=df[item]
    y=df['CO2EMISSIONS']
    x_train , x_test , y_train , y_test=train_test_split(x,y,test_size=0.2)
    regression= LinearRegression()
    regression.fit(x_train, y_train)
    preds=regression.predict(x_test)
    erroe_rmse=root_mean_squared_error(y_test, preds)
    error_mae=mean_absolute_error(y_test, preds)
    error_mse=mean_squared_error(y_test, preds)
    print(f"column:{item}:ðŸ“ˆ RMSE={erroe_rmse:.4f} â€¢ ðŸ“‰ MAE={error_mae:.4f} â€¢ ðŸ§® MSE={error_mse:.4f}")
    metrics.append((item,erroe_rmse,error_mae,error_mse))
error_df=pd.DataFrame(metrics,columns=['column','root_mean_squared_error','mean_absolute_error','mean_squared_error'])  
error_df

column:['FUELCONSUMPTION_COMB_MPG']:ðŸ“ˆ RMSE=24.2341 â€¢ ðŸ“‰ MAE=16.0672 â€¢ ðŸ§® MSE=587.2892
column:['FUELCONSUMPTION_COMB']:ðŸ“ˆ RMSE=30.0445 â€¢ ðŸ“‰ MAE=20.8205 â€¢ ðŸ§® MSE=902.6723
column:['FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=32.6973 â€¢ ðŸ“‰ MAE=24.5048 â€¢ ðŸ§® MSE=1069.1104
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB']:ðŸ“ˆ RMSE=26.1189 â€¢ ðŸ“‰ MAE=16.1202 â€¢ ðŸ§® MSE=682.1948
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=26.5678 â€¢ ðŸ“‰ MAE=17.1950 â€¢ ðŸ§® MSE=705.8468
column:['FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=27.5394 â€¢ ðŸ“‰ MAE=19.1229 â€¢ ðŸ§® MSE=758.4174
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=23.9777 â€¢ ðŸ“‰ MAE=15.2332 â€¢ ðŸ§® MSE=574.9295

                                              column  ...  mean_squared_error
0                         [FUELCONSUMPTION_COMB_MPG]  ...          587.289208
1                             [FUELCONSUMPTION_COMB]  ...          902.672261
2                              [FUELCONSUMPTION_HWY]  ...         1069.110443
3   [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COMB]  ...          682.194760
4    [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_HWY]  ...          705.846835
5        [FUELCONSUMPTION_COMB, FUELCONSUMPTION_HWY]  ...          758.417450
6  [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COM...  ...          574.929522

[7 rows x 4 columns]

In [21]:
error_df.sort_values(by='mean_absolute_error',ascending=True)

                                              column  ...  mean_squared_error
6  [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COM...  ...          574.929522
0                         [FUELCONSUMPTION_COMB_MPG]  ...          587.289208
3   [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COMB]  ...          682.194760
4    [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_HWY]  ...          705.846835
5        [FUELCONSUMPTION_COMB, FUELCONSUMPTION_HWY]  ...          758.417450
1                             [FUELCONSUMPTION_COMB]  ...          902.672261
2                              [FUELCONSUMPTION_HWY]  ...         1069.110443

[7 rows x 4 columns]

# ---------------------------------------------------------------------

In [24]:
# import itertools
# cols = ['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']
# subsets = []
# for r in range(1, len(cols)+1):
#     subsets.extend(itertools.combinations(cols, r))

# subsets = [list(s) for s in subsets]

# print(subsets)

import itertools

cols = ['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']
subsets = [list(s) for r in range(1, len(cols)+1) for s in itertools.combinations(cols, r)]

print(subsets)

[['FUELCONSUMPTION_COMB_MPG'], ['FUELCONSUMPTION_COMB'], ['FUELCONSUMPTION_HWY'], ['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB'], ['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_HWY'], ['FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY'], ['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']]

In [25]:
metrics=[]
for item in subsets:
    x=df[item]
    y=df['CO2EMISSIONS']
    x_train , x_test , y_train , y_test=train_test_split(x,y,test_size=0.2)
    regression= LinearRegression()
    regression.fit(x_train, y_train)
    preds=regression.predict(x_test)
    erroe_rmse=root_mean_squared_error(y_test, preds)
    error_mae=mean_absolute_error(y_test, preds)
    error_mse=mean_squared_error(y_test, preds)
    print(f"column:{item}:ðŸ“ˆ RMSE={erroe_rmse:.4f} â€¢ ðŸ“‰ MAE={error_mae:.4f} â€¢ ðŸ§® MSE={error_mse:.4f}")
    metrics.append((item,erroe_rmse,error_mae,error_mse))
error_df=pd.DataFrame(metrics,columns=['column','root_mean_squared_error','mean_absolute_error','mean_squared_error'])  
error_df

column:['FUELCONSUMPTION_COMB_MPG']:ðŸ“ˆ RMSE=27.2153 â€¢ ðŸ“‰ MAE=18.6216 â€¢ ðŸ§® MSE=740.6722
column:['FUELCONSUMPTION_COMB']:ðŸ“ˆ RMSE=29.7949 â€¢ ðŸ“‰ MAE=21.8978 â€¢ ðŸ§® MSE=887.7340
column:['FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=31.7158 â€¢ ðŸ“‰ MAE=23.7010 â€¢ ðŸ§® MSE=1005.8951
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB']:ðŸ“ˆ RMSE=21.5505 â€¢ ðŸ“‰ MAE=13.7566 â€¢ ðŸ§® MSE=464.4245
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=24.6174 â€¢ ðŸ“‰ MAE=16.3154 â€¢ ðŸ§® MSE=606.0156
column:['FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=27.5962 â€¢ ðŸ“‰ MAE=20.0711 â€¢ ðŸ§® MSE=761.5503
column:['FUELCONSUMPTION_COMB_MPG', 'FUELCONSUMPTION_COMB', 'FUELCONSUMPTION_HWY']:ðŸ“ˆ RMSE=24.9699 â€¢ ðŸ“‰ MAE=15.2632 â€¢ ðŸ§® MSE=623.4964

                                              column  ...  mean_squared_error
0                         [FUELCONSUMPTION_COMB_MPG]  ...          740.672201
1                             [FUELCONSUMPTION_COMB]  ...          887.734036
2                              [FUELCONSUMPTION_HWY]  ...         1005.895080
3   [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COMB]  ...          464.424486
4    [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_HWY]  ...          606.015636
5        [FUELCONSUMPTION_COMB, FUELCONSUMPTION_HWY]  ...          761.550255
6  [FUELCONSUMPTION_COMB_MPG, FUELCONSUMPTION_COM...  ...          623.496438

[7 rows x 4 columns]